#!/usr/bin/env python3
"""Check this schema against a real Stripe Sigma account and report the differences.

Stripe publishes the authoritative column list only inside the Dashboard schema
browser, so anything this dataset marks `community` is unproven. Run this against
your own account to confirm what exists, find columns we're missing, and flag
columns that don't exist. The output is a patch file you can contribute back.

Sigma has no direct SQL-over-HTTP endpoint, so this works from query results you
export. Two supported inputs:

  --probe-sql   Print a SQL script to run in the Sigma query editor. It returns
                one row per (table, column) for every table in this schema.

  --results     A CSV exported from that query, with columns `table_name` and
                `column_name`. Compares it against the schema and writes a report.

Example:
    python3 tools/verify_against_sigma.py --probe-sql > probe.sql
    # run probe.sql in https://dashboard.stripe.com/sigma/queries, export CSV
    python3 tools/verify_against_sigma.py --results sigma_export.csv -o build/verification.json

Nothing here talks to Stripe directly, so no API keys are involved.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path


def build_probe_sql(schema: dict) -> str:
    """Emit a query that reports each table's columns as data.

    `select * from <t> limit 0` gives Sigma's real column list per table, but the
    editor returns one result set. Instead we union a zero-row probe per table so
    the export carries the column names in the header of each block.
    """
    lines = [
        "-- Generated by tools/verify_against_sigma.py",
        "-- Run in the Sigma query editor, then export the result as CSV.",
        "-- Each block returns 0 rows; the value is in confirming the query PARSES,",
        "-- which proves every column named in it exists.",
        "--",
        "-- Run blocks individually: a single failing column fails the whole union.",
        "",
    ]
    for table in schema["tables"]:
        if not table["columns"]:
            continue
        cols = ", ".join(c["name"] for c in table["columns"])
        lines.append(f"-- {table['name']}: {len(table['columns'])} columns")
        lines.append(f"select {cols} from {table['name']} limit 0;")
        lines.append("")
    return "\n".join(lines)


def load_results(path: Path) -> dict[str, set[str]]:
    actual: dict[str, set[str]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fields = {f.lower() for f in (reader.fieldnames or [])}
        if not {"table_name", "column_name"} <= fields:
            raise SystemExit(
                "results CSV must have `table_name` and `column_name` columns; "
                f"got {sorted(fields)}"
            )
        for row in reader:
            table = (row.get("table_name") or "").strip()
            column = (row.get("column_name") or "").strip()
            if table and column:
                actual.setdefault(table, set()).add(column)
    return actual


def compare(schema: dict, actual: dict[str, set[str]]) -> dict:
    report = {
        "tables_checked": len(actual),
        "missing_tables": [],
        "unknown_tables": [],
        "per_table": {},
        "summary": {"confirmed": 0, "missing_from_schema": 0, "not_in_account": 0},
    }
    tables = {t["name"]: t for t in schema["tables"]}

    for name in sorted(set(tables) - set(actual)):
        report["missing_tables"].append(name)
    for name in sorted(set(actual) - set(tables)):
        report["unknown_tables"].append(name)

    for name in sorted(set(tables) & set(actual)):
        declared = {c["name"] for c in tables[name]["columns"]}
        live = actual[name]
        confirmed = sorted(declared & live)
        missing_from_schema = sorted(live - declared)
        not_in_account = sorted(declared - live)

        report["summary"]["confirmed"] += len(confirmed)
        report["summary"]["missing_from_schema"] += len(missing_from_schema)
        report["summary"]["not_in_account"] += len(not_in_account)

        if missing_from_schema or not_in_account:
            report["per_table"][name] = {
                "confirmed": confirmed,
                "missing_from_schema": missing_from_schema,
                "not_in_account": not_in_account,
            }
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--schema", type=Path, default=Path("dist/sigma_schema.json"))
    parser.add_argument("--probe-sql", action="store_true",
                        help="print the probe SQL to run in Sigma and exit")
    parser.add_argument("--results", type=Path,
                        help="CSV exported from Sigma with table_name,column_name")
    parser.add_argument("-o", "--output", type=Path, default=Path("build/verification.json"))
    args = parser.parse_args()

    schema = json.loads(args.schema.read_text(encoding="utf-8"))

    if args.probe_sql:
        print(build_probe_sql(schema))
        return 0

    if not args.results:
        parser.error("pass --probe-sql to generate the query, or --results to compare an export")

    report = compare(schema, load_results(args.results))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    summary = report["summary"]
    print(f"tables checked:        {report['tables_checked']}")
    print(f"columns confirmed:     {summary['confirmed']}")
    print(f"missing from schema:   {summary['missing_from_schema']}")
    print(f"declared but absent:   {summary['not_in_account']}")
    if report["unknown_tables"]:
        print(f"tables we don't list:  {', '.join(report['unknown_tables'][:10])}")
    print(f"\nfull report -> {args.output}")
    print("Please open a PR with this report so everyone benefits.")

    # Differences are the expected outcome, not a failure — accounts differ by
    # which Stripe products they have enabled.
    return 0


if __name__ == "__main__":
    sys.exit(main())
